name: Deploy Web to Vercel

on:
  workflow_run:
    workflows: [Run Turbo Tasks]
    types:
      - completed

jobs:
  Deploy-Web:
    runs-on: ubuntu-latest
    steps:
      # checkout and setup (ì´ì „ ì›Œí¬í”Œë¡œìš°ì—ì„œ ì´ë¯¸ ì„¤ì¹˜í•œ pnpm ë“±ì„ ì¬ì„¤ì¹˜í•  í•„ìš” ì—†ìŒ)
      - uses: actions/checkout@v4

      # deploy Web to vercel
      - name: Deploy Web to Vercel
        run: |
          npm install --global vercel@latest
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_ACCESS_TOKEN }}
      - name: Get Web Preview
        uses: zentered/vercel-preview-url@v1.1.9
        id: vercel_preview_url_web
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
        with:
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
      - name: Get Web preview URL
        run: echo "https://${{ steps.vercel_preview_url_web.outputs.preview_url }}"
      - name: Send Web Discord Notification
        env:
          DATA: |
            {
              "content": "<@stakbucks>",
              "embeds": [
                {
                  "title": "ğŸ‘€ Web ë¯¸ë¦¬ë³´ê¸°ê°€ ì¤€ë¹„ë˜ì—ˆì–´ìš”",
                  "description": "ğŸ‘‰ https://${{ steps.vercel_preview_url_web.outputs.preview_url }}",
                  "color": 65280
                }
              ]
            }
        run: |
          curl -X POST -H 'Content-type: application/json' \
          -d "$DATA" \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
